Traceback (most recent call last):
  File "/home/vagrant/holbertonschool-higher_level_programming/0x05-python-exceptions/100-safe_print_integer_err.py", line 5, in safe_print_integer_err
    print("{:d}".format(value))
ValueError: Unknown format code 'd' for object of type 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    has_been_print = safe_print_integer_err(value)
  File "/home/vagrant/holbertonschool-higher_level_programming/0x05-python-exceptions/100-safe_print_integer_err.py", line 8, in safe_print_integer_err
    print(e, file=2)
AttributeError: 'int' object has no attribute 'write'
